# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/bwmarrin/dgvoice"

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  revision = "b37325c2241b2fdde154900432a36c98f469a4d4"

[[constraint]]
  branch = "master"
  name = "github.com/gyuho/goling"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
